<?php require_once dirname(__DIR__) . '/public-layout.php'; ?>
<?php if ($actor['role'] === 'official'): ?>
<?php if ($c['team'] && empty($c['assignedUserId']) && in_array($c['status'], ['Assigned', 'In Progress'], true)): ?><p class="info-callout">This legacy record has a team assignment. Select a specific personnel account below to give them private access and send the assignment email.</p><?php endif ?>
<?php if (br_review($c)): ?>
<section class="action-panel"><h3>Assess &amp; recommend</h3><p>Review the suggestions and evidence, then record the official plan.</p>
<form method="post" action="api.php" data-action="assess" data-id="<?= h($c['id']) ?>"><?php require __DIR__ . '/priority-recommendation.php'; ?><label class="form-label">Priority<select class="form-select" name="priority" required><?php br_options(ComplaintWorkflow::PRIORITIES, $c['priority']); ?></select></label><label class="form-label" for="recommendation">Official recommendation</label><textarea class="form-control" id="recommendation" name="recommendation" required maxlength="4000" rows="3"><?= h($c['recommendation']) ?></textarea><label class="form-label mt-3">Assessment notes (optional)<textarea class="form-control" name="assessment" maxlength="3000"><?= h($c['assessment']) ?></textarea></label><button class="btn btn-primary mt-3" type="submit">Save assessment</button></form>
<details class="mt-4"><summary>Return for staff inspection, refer, or reject</summary><form class="mt-3" method="post" action="api.php" data-action="exception" data-id="<?= h($c['id']) ?>"><label class="form-label">Outcome<select id="exception-status" name="status" class="form-select"><?php br_options(['Returned for Information', 'Referred to Another Office', 'Rejected'], 'Returned for Information'); ?></select></label><p class="form-text">Anonymous reporters cannot be contacted. Staff must gather any missing information on site.</p><div id="office-wrap" hidden><label class="form-label">Receiving office<input class="form-control" id="receiving-office" name="office" maxlength="200"></label></div><label class="form-label">Reason and next steps<textarea class="form-control" name="notes" maxlength="3000" required></textarea></label><button class="btn btn-light" type="submit">Record outcome</button></form></details></section>
<?php endif ?>
<?php if (in_array($c['status'], ['Under Review', 'Assigned', 'In Progress'], true) && $c['recommendation'] !== ''):
    $staff = array_filter(br_store()->workloads($actor['id']), fn($u) => $u['active']); $recommendedWorker = ConcernInsights::recommendPersonnel($staff,$c); ?>
<section class="action-panel"><h3>Assign / change personnel</h3><?php if ($recommendedWorker): ?><p class="priority-advice"><strong>Recommended personnel: <?= h($recommendedWorker['name']) ?></strong><br><?= (int)$recommendedWorker['active_work'] ?> active task(s) · <?= h($recommendedWorker['team']) ?><br><small>Relevant team first, then fewest active tasks. You can choose any active personnel below.</small></p><?php endif ?><form method="post" action="api.php" data-action="assign" data-id="<?= h($c['id']) ?>"><label class="form-label">Responsible personnel<select name="personnelId" class="form-select" required><option value="">Choose personnel</option><?php foreach ($staff as $u): ?><option value="<?= h($u['id']) ?>"<?= ($c['assignedUserId'] ?? '') === $u['id'] ? ' selected' : '' ?>><?= h($u['name'] . ' — ' . $u['team'] . ' · ' . $u['active_work'] . ' active · ' . ConcernInsights::workloadLabel((int)$u['active_work']) . (($recommendedWorker['id'] ?? '') === $u['id'] ? ' · Recommended' : '')) ?></option><?php endforeach ?></select></label><label class="form-label">Target completion (optional, Asia/Manila)<input type="datetime-local" class="form-control" name="dueAt" value="<?= !empty($c['dueAt']) ? h(date('Y-m-d\TH:i',(int)$c['dueAt'])) : '' ?>"></label><p class="form-text">The selected person receives an email and in-app notification. Reassignment removes the previous person's access and returns work to Assigned; earlier evidence stays in the timeline.</p><button class="btn btn-primary" type="submit">Save assignment</button></form></section>
<?php endif ?>
<?php if ($c['status'] === 'Resolved'): ?>
<section class="action-panel"><h3>Review completed work</h3><form method="post" action="api.php" data-action="verification" data-id="<?= h($c['id']) ?>"><label class="form-label">Review notes (required to reopen)<textarea class="form-control" id="feedback" name="feedback" maxlength="3000"></textarea></label><div class="d-flex gap-2 flex-wrap"><button class="btn btn-light" type="submit" value="reopen">Reopen Concern</button><button class="btn btn-primary" type="submit" value="verify">Close Concern</button></div></form></section>
<?php elseif (in_array($c['status'], ['Verified', 'Rejected', 'Referred to Another Office'], true)): ?>
<section class="action-panel"><h3>Reopen for assessment</h3><form method="post" action="api.php" data-action="reopen" data-id="<?= h($c['id']) ?>"><label class="form-label">Reason<textarea id="feedback" name="feedback" class="form-control" required maxlength="3000"></textarea></label><button type="submit" class="btn btn-light">Reopen Concern</button></form></section>
<?php elseif ($c['status'] === 'Returned for Information'): ?>
<section class="action-panel"><h3>Record follow-up inspection</h3><form method="post" action="api.php" data-action="information" data-id="<?= h($c['id']) ?>"><label class="form-label">Information gathered<textarea name="notes" class="form-control" required maxlength="2000"></textarea></label><?php br_upload('information-photo', 'Updated supporting photo'); ?><button type="submit" class="btn btn-primary mt-3">Return to assessment</button></form></section>
<?php endif ?>
<details class="action-panel"><summary>Edit concern information / priority</summary><form class="mt-3" method="post" action="api.php" data-action="edit" data-id="<?= h($c['id']) ?>"><?php require __DIR__ . '/priority-recommendation.php'; ?>
<?php if (!empty($c['concernType'])) { br_concern_choices($c); br_location_fields($c['locationDetails']); } else { ?><label class="form-label">Category<select class="form-select" name="category" required><?php br_options(ComplaintWorkflow::CATEGORIES, $c['category']); ?></select></label><label class="form-label">Private location<input class="form-control" name="location" value="<?= h($c['location']) ?>" required maxlength="500"></label><?php } ?>
<label class="form-label">Priority<select class="form-select" name="priority" required><?php br_options(ComplaintWorkflow::PRIORITIES, $c['priority']); ?></select></label><label class="form-label">Additional details (optional)<textarea class="form-control" name="description" maxlength="4000"><?= h($c['description']) ?></textarea></label><label class="form-label">Official recommendation<textarea class="form-control" name="recommendation" maxlength="4000"><?= h($c['recommendation']) ?></textarea></label><button class="btn btn-primary" type="submit">Save concern information</button></form></details>
<?php endif ?>
<?php if (in_array($c['status'], ['Assigned', 'In Progress'], true) && ($actor['role'] === 'official' || ComplaintWorkflow::canSee($c, $actor))): ?>
<?php foreach ($c['status'] === 'Assigned' ? ['start' => 'Start work'] : ['note' => 'Record progress', 'resolve' => 'Complete / resolve work'] as $action => $label): ?>
<section class="action-panel"><h3><?= h($label) ?></h3><form method="post" action="api.php" data-action="<?= $action ?>" data-id="<?= h($c['id']) ?>"><label class="form-label">Work status<select class="form-select" name="workStatus" required><?php br_options($action === 'resolve' ? ['Fully repaired'] : ConcernCatalog::WORK_STATUSES, $action === 'resolve' ? 'Fully repaired' : 'Arrived at location'); ?></select></label><fieldset class="mb-3"><legend class="form-label">Action taken (select at least one)</legend><div class="choice-grid"><?php foreach (ConcernCatalog::ACTIONS as $value): ?><label class="choice-card"><input class="form-check-input" type="checkbox" name="actions" value="<?= h($value) ?>"><span><?= h($value) ?></span></label><?php endforeach ?></div></fieldset><label class="form-label">Additional notes (optional; required for Other)<textarea class="form-control" name="notes" maxlength="4000" rows="2"></textarea></label><?php br_upload($action . '-photo', $action === 'resolve' ? 'Completion evidence' : 'Work evidence', true); ?><p class="form-text">Image evidence is required. The official reviews completed work before closing the concern.</p><button class="btn btn-primary" type="submit"><?= h($label) ?></button></form></section>
<?php endforeach; endif ?>
