<?php
require_once dirname(__DIR__) . '/public-layout.php';
$primaryConcern = $c['primaryConcern'] ?? null;
$isLinkedConcern = !empty($c['linkedPrimaryId']) || !empty($c['primaryConcernId']) || is_array($primaryConcern);
$currentBlock = !empty($c['blocked']['active']) ? $c['blocked'] : null;
$pendingInformationRequest = !empty($c['informationRequestPending']);
?>
<?php if (!empty($c['isOwn']) && $pendingInformationRequest && !$isLinkedConcern): ?>
<section class="action-panel" data-workflow-section="reporter-information"><h3>Provide more information</h3><p>Respond to the barangay's request about your concern.</p><form method="post" action="api.php" data-action="information" data-id="<?= h($c['id']) ?>"><label class="form-label">Additional information<textarea class="form-control" name="description" maxlength="4000" rows="3" required></textarea></label><?php br_upload('followup-photo', 'Photo (optional)'); ?><button class="btn btn-primary" type="submit">Send information</button></form></section>
<?php endif ?>
<?php if ($actor['role'] === 'official'): ?>
<?php if ($pendingInformationRequest): ?><section class="action-panel" data-workflow-section="waiting-information"><h3>Reporter information requested</h3><p>The reporter can respond through the <?= ($c['reporterChannel'] ?? 'tracking') === 'account' ? 'MaintainPro account/dashboard' : 'private tracking page' ?>. Assessment, assignment, and work may continue while the response is pending.</p><?php if (!empty($c['informationRequest']['message'])): ?><p class="form-text mb-0">Requested: <?= h($c['informationRequest']['message']) ?></p><?php endif ?></section><?php endif ?>
<?php if (br_review($c) && !$isLinkedConcern): ?>
<section class="action-panel<?= empty($c['recommendation'])?' action-primary':'' ?>" data-workflow-section="assessment"><h3><?= empty($c['recommendation'])?'Next step: Assess concern':'Update assessment' ?></h3><p>Review the reported concern and evidence, then record the official plan for staff to carry out.</p>
<form method="post" action="api.php" data-action="assess" data-id="<?= h($c['id']) ?>"><?php require __DIR__ . '/priority-recommendation.php'; ?><label class="form-label">Priority<select class="form-select" name="priority" required><?php br_options(ComplaintWorkflow::PRIORITIES, $c['priority']); ?></select></label><?php require __DIR__ . '/sla-recommendation.php'; ?><label class="form-label" for="recommendation">Official recommendation</label><textarea class="form-control" id="recommendation" name="recommendation" required maxlength="4000" rows="3"><?= h($c['recommendation']) ?></textarea><label class="form-label">Assessment notes (optional)<textarea class="form-control" name="assessment" maxlength="3000"><?= h($c['assessment']) ?></textarea></label><button class="btn btn-primary" type="submit">Save assessment</button></form>
<details class="mt-4"><summary>Request More Information</summary><form class="mt-3" method="post" action="api.php" data-action="request_information" data-id="<?= h($c['id']) ?>"><label class="form-label">Information needed<textarea class="form-control" name="notes" maxlength="3000" rows="3" required placeholder="Clearly describe what the reporter should clarify or photograph."></textarea></label><p class="form-text"><?= ($c['reporterChannel'] ?? 'tracking') === 'account' ? 'The request will appear in the reporter\'s MaintainPro account/dashboard.' : 'The request will appear on the private tracking page. The reporter must use the original reference number and tracking code to respond.' ?> Assessment and assignment can continue while the response is pending.</p><button class="btn btn-light" type="submit">Send information request</button></form></details>
<details class="mt-3"><summary>Reject concern</summary><form class="mt-3" method="post" action="api.php" data-action="exception" data-id="<?= h($c['id']) ?>"><input type="hidden" name="status" value="Rejected"><label class="form-label">Rejection reason and next steps<textarea class="form-control" name="notes" maxlength="3000" required></textarea></label><p class="form-text">Rejecting ends the normal work stages. The reason remains in the concern timeline, and an official may reopen the concern later.</p><button class="btn btn-danger" type="submit">Reject concern</button></form></details></section>
<?php endif ?>
<?php
$linkCandidates = is_array($c['linkCandidates'] ?? null) ? $c['linkCandidates'] : [];
if (!$linkCandidates && isset($related) && is_array($related)) {
    $linkCandidates = array_values(array_filter($related, fn($candidate) => ($candidate['id'] ?? '') !== $c['id']));
}
?>
<?php if (!$isLinkedConcern && $c['status'] !== 'Verified'): ?>
<details class="action-panel" data-workflow-section="link-concern"><summary>Link to Existing Concern</summary><form class="mt-3" method="post" action="api.php" data-action="link_concern" data-id="<?= h($c['id']) ?>"><label class="form-label">Primary concern reference<input class="form-control" name="primaryConcernId" list="primary-concern-options" required maxlength="64" placeholder="CON-2026-000001"></label><datalist id="primary-concern-options"><?php foreach ($linkCandidates as $candidate): ?><option value="<?= h($candidate['id'] ?? '') ?>"><?= h(br_status_label($candidate['status'] ?? 'Submitted')) ?></option><?php endforeach ?></datalist><p class="form-text">Choose a suggested reference or enter another concern reference after reviewing it.</p><label class="form-label">Link note (optional)<textarea class="form-control" name="notes" maxlength="1000" rows="2" placeholder="Why these reports describe the same physical issue"></textarea></label><p class="form-text">The report and its reference number remain recorded. Work and public progress will follow the selected primary concern; a separate duplicate assignment will not be created.</p><button class="btn btn-light" type="submit">Link as same issue</button></form></details>
<?php endif ?>
<?php if (!$isLinkedConcern && in_array($c['status'], ['Under Review', 'Assigned', 'In Progress', 'Returned for Information'], true) && $c['recommendation'] !== ''):
    $recommendedTeam=ConcernInsights::relevantTeam($c); ?>
<section class="action-panel" data-workflow-section="assignment"><h3>Assign / change team or crew</h3><?php if ($recommendedTeam): ?><p class="priority-advice"><strong>Recommended team/crew: <?= h($recommendedTeam) ?></strong><br><small>Based on the concern category. The official remains responsible for the final team choice.</small></p><?php endif ?><form method="post" action="api.php" data-action="assign" data-id="<?= h($c['id']) ?>"><label class="form-label">Assigned team/crew<select name="team" class="form-select" required><?php br_options(ComplaintWorkflow::TEAMS,$c['team'] ?: $recommendedTeam,'Choose team or crew'); ?></select></label><label class="form-label">Target completion (optional, Asia/Manila)<input type="datetime-local" class="form-control" name="dueAt" value="<?= !empty($c['dueAt']) ? h(date('Y-m-d\TH:i',(int)$c['dueAt'])) : '' ?>"></label><p class="form-text">All active, verified personnel in the selected team receive an in-app notification and may accept the work. Assigning again closes the previous offer without removing historical records.</p><button class="btn btn-primary" type="submit">Assign to team</button></form></section>
<?php endif ?>
<?php if (!empty($c['teamAssignment'])): $assignment=$c['teamAssignment']; ?>
<section class="action-panel" data-workflow-section="team-response-progress"><h3>Team response progress</h3><p>Assigned team/crew: <strong><?= h($assignment['team']) ?></strong> · Status: <strong><?= h(ucfirst($assignment['status'])) ?></strong></p><div class="d-flex flex-wrap gap-2"><span class="status status-assigned">Notified <?= (int)$assignment['notified'] ?></span><span class="status status-verified">Accepted <?= (int)$assignment['accepted'] ?></span><span class="status status-rejected">Declined <?= (int)$assignment['declined'] ?></span><span class="status">Pending <?= (int)$assignment['pending'] ?></span></div></section>
<?php endif ?>
<?php if ($c['status'] === 'Resolved'): ?>
<section class="action-panel" data-workflow-section="resolution-review"><h3>Review completed work</h3><form method="post" action="api.php" data-action="verification" data-id="<?= h($c['id']) ?>"><label class="form-label">Review notes (required to reopen)<textarea class="form-control" id="feedback" name="feedback" maxlength="3000"></textarea></label><div class="d-flex gap-2 flex-wrap"><button class="btn btn-light" type="submit" value="reopen">Reopen Concern</button><button class="btn btn-primary" type="submit" value="verify">Close Concern</button></div></form></section>
<?php elseif (in_array($c['status'], ['Verified', 'Rejected', 'Referred to Another Office'], true)): ?>
<section class="action-panel" data-workflow-section="reopen"><h3>Reopen for assessment</h3><form method="post" action="api.php" data-action="reopen" data-id="<?= h($c['id']) ?>"><label class="form-label">Reason<textarea id="feedback" name="feedback" class="form-control" required maxlength="3000"></textarea></label><button type="submit" class="btn btn-light">Reopen Concern</button></form></section>
<?php endif ?>
<?php endif ?>
<?php if ($actor['role']==='personnel' && !empty($c['teamOffer'])): ?>
<section class="action-panel action-primary" data-workflow-section="team-work-offer"><h3>Pending work offer</h3><p>This concern was assigned to <strong><?= h($c['team']) ?></strong>. Accept it only if you are available; the first valid acceptance becomes the responsible worker.</p><div class="d-flex flex-wrap gap-2"><form method="post" action="api.php" data-action="accept_work" data-id="<?= h($c['id']) ?>"><button class="btn btn-primary" type="submit">Accept Work</button></form><form method="post" action="api.php" data-action="decline_work" data-id="<?= h($c['id']) ?>"><button class="btn btn-danger" type="submit">Not Available</button></form></div></section>
<?php endif ?>
<?php if ($currentBlock): ?>
<section class="action-panel" data-workflow-section="blocked-status"><h3 class="section-title">Work blocked / delayed</h3><p><strong><?= h($currentBlock['reason']) ?></strong></p><p><?= h($currentBlock['recommendedAction']) ?></p><?php if (!empty($currentBlock['officialInstructions'])): ?><p>Official instructions: <?= h($currentBlock['officialInstructions']) ?></p><?php endif ?></section>
<?php endif ?>
<?php if ($currentBlock && $actor['role'] === 'official'): ?>
<section class="action-panel blocked-management" data-workflow-section="blocked-management"><h3>Manage blocked work</h3><div class="blocked-summary"><p><strong><?= h($currentBlock['reason'] ?? 'Blocked work') ?></strong></p><?php if (!empty($currentBlock['recommendedAction'])): ?><p>Recommended action: <?= h($currentBlock['recommendedAction']) ?></p><?php endif ?><?php if (!empty($currentBlock['expectedAt'])): ?><p>Expected availability: <?= h(br_date((string)$currentBlock['expectedAt'], true)) ?></p><?php endif ?></div><form method="post" action="api.php" data-action="manage_block" data-id="<?= h($c['id']) ?>"><label class="form-label">Official decision<select class="form-select" name="decision" required><option value="">Choose an action</option><option value="approve">Approve requested action</option><option value="instructions">Send / update instructions</option><option value="resume">Clear block and resume work</option></select></label><label class="form-label">Instructions (required unless resuming work)<textarea class="form-control" name="instructions" maxlength="2000" rows="3"></textarea></label><label class="form-label">Updated target completion (optional, Asia/Manila)<input class="form-control" type="datetime-local" name="dueAt" value="<?= !empty($c['dueAt']) ? h(date('Y-m-d\TH:i', (int)$c['dueAt'])) : '' ?>"></label><button class="btn btn-primary" type="submit">Save blocked-work decision</button></form></section>
<?php endif ?>
<?php if (!$isLinkedConcern && in_array($c['status'], ['Assigned', 'In Progress'], true) && !empty($c['canWork'])): ?>
<?php if (!$currentBlock): ?>
<details class="action-panel" data-workflow-section="block-work"><summary>Mark work as blocked / delayed</summary><form class="mt-3" method="post" action="api.php" data-action="block" data-id="<?= h($c['id']) ?>"><label class="form-label">Block reason<select class="form-select" name="blockReason" required><option value="">Choose a reason</option><?php br_options(ConcernCatalog::BLOCK_REASONS); ?></select></label><label class="form-label">Notes (optional)<textarea class="form-control" name="blockNotes" maxlength="2000" rows="2"></textarea></label><label class="form-label">Recommended action<textarea class="form-control" name="recommendedAction" maxlength="1500" rows="2" required placeholder="What should happen before work can continue?"></textarea></label><label class="form-label">Expected availability (optional, Asia/Manila)<input class="form-control" type="date" name="expectedAt"></label><?php br_upload('block-photo', 'Supporting photo'); ?><p class="form-text">The reason, recommendations, expected date, and any supporting photo are recorded in the concern timeline. Officials will be notified.</p><button class="btn btn-danger" type="submit">Mark as blocked</button></form></details>
<?php endif ?>
<?php foreach ($c['status'] === 'Assigned' ? ['start' => 'Start work'] : ['note' => 'Record progress', 'resolve' => 'Complete / resolve work'] as $action => $label): ?>
<?php $workStatuses = $action === 'resolve' ? ['Fully repaired'] : array_values(array_diff(ConcernCatalog::WORK_STATUSES, ['Materials required', 'Waiting for materials', 'Unable to complete', 'Requires another team'])); ?>
<section class="action-panel" data-workflow-section="<?= $action === 'start' ? 'work-start' : ($action === 'note' ? 'work-progress' : 'work-resolution') ?>"><h3><?= h($label) ?></h3><?php if ($currentBlock): ?><p class="info-callout">This concern is currently marked blocked. Recording a new work update will indicate that work has resumed.</p><?php endif ?><form method="post" action="api.php" data-action="<?= $action ?>" data-id="<?= h($c['id']) ?>"><label class="form-label">Work status<select class="form-select" name="workStatus" required><?php br_options($workStatuses, $action === 'resolve' ? 'Fully repaired' : 'Arrived at location'); ?></select></label><fieldset class="mb-3"><legend class="form-label">Action taken (select at least one)</legend><div class="choice-grid"><?php foreach (ConcernCatalog::ACTIONS as $value): ?><label class="choice-card"><input class="form-check-input" type="checkbox" name="actions" value="<?= h($value) ?>"><span><?= h($value) ?></span></label><?php endforeach ?></div></fieldset><label class="form-label">Additional notes (optional; required for Other)<textarea class="form-control" name="notes" maxlength="4000" rows="2"></textarea></label><?php br_upload($action . '-photo', $action === 'resolve' ? 'Completion evidence' : 'Work evidence', true); ?><p class="form-text">Image evidence is required. The official reviews completed work before closing the concern.</p><button class="btn btn-primary" type="submit"><?= h($label) ?></button></form></section>
<?php endforeach; endif ?>
