<?php
require_once dirname(__DIR__) . '/public-layout.php';
$primaryConcern = $c['primaryConcern'] ?? null;
$isLinkedConcern = !empty($c['primaryConcernId']) || is_array($primaryConcern);
$currentBlock = is_array($c['block'] ?? null) && empty($c['block']['resolvedAt']) ? $c['block'] : null;
?>
<?php if ($actor['role'] === 'official'): ?>
<?php if ($c['team'] && empty($c['assignedUserId']) && in_array($c['status'], ['Assigned', 'In Progress'], true)): ?><p class="info-callout">This legacy record has a team assignment. Select a specific personnel account below to give them private access and send the assignment email.</p><?php endif ?>
<?php if (br_review($c) && !$isLinkedConcern): ?>
<section class="action-panel"><h3>Assess &amp; recommend</h3><p>Review the reported concern and evidence, then record the official plan for staff to carry out.</p>
<form method="post" action="api.php" data-action="assess" data-id="<?= h($c['id']) ?>"><?php require __DIR__ . '/priority-recommendation.php'; ?><label class="form-label">Priority<select class="form-select" name="priority" required><?php br_options(ComplaintWorkflow::PRIORITIES, $c['priority']); ?></select></label><label class="form-label" for="recommendation">Official recommendation</label><textarea class="form-control" id="recommendation" name="recommendation" required maxlength="4000" rows="3"><?= h($c['recommendation']) ?></textarea><label class="form-label mt-3">Assessment notes (optional)<textarea class="form-control" name="assessment" maxlength="3000"><?= h($c['assessment']) ?></textarea></label><button class="btn btn-primary mt-3" type="submit">Save assessment</button></form>
<details class="mt-4"><summary>Request More Information</summary><form class="mt-3" method="post" action="api.php" data-action="request_information" data-id="<?= h($c['id']) ?>"><label class="form-label">Information needed<textarea class="form-control" name="notes" maxlength="3000" rows="3" required placeholder="Clearly describe what the reporter should clarify or photograph."></textarea></label><p class="form-text">This request will appear on the private tracking page. The reporter must use the original reference number and tracking code to respond.</p><button class="btn btn-light" type="submit">Send information request</button></form></details>
<details class="mt-3"><summary>Refer or reject concern</summary><form class="mt-3" method="post" action="api.php" data-action="exception" data-id="<?= h($c['id']) ?>"><label class="form-label">Outcome<select id="exception-status" name="status" class="form-select"><?php br_options(['Referred to Another Office', 'Rejected'], 'Referred to Another Office'); ?></select></label><div id="office-wrap"><label class="form-label">Receiving office<input class="form-control" id="receiving-office" name="office" maxlength="200" required></label></div><label class="form-label">Reason and next steps<textarea class="form-control" name="notes" maxlength="3000" required></textarea></label><button class="btn btn-light" type="submit">Record outcome</button></form></details></section>
<?php endif ?>
<?php
$linkCandidates = is_array($c['linkCandidates'] ?? null) ? $c['linkCandidates'] : [];
if (!$linkCandidates && isset($related) && is_array($related)) {
    $linkCandidates = array_values(array_filter($related, fn($candidate) => ($candidate['id'] ?? '') !== $c['id']));
}
?>
<?php if (!$isLinkedConcern && $linkCandidates): ?>
<details class="action-panel"><summary>Link to Existing Concern</summary><form class="mt-3" method="post" action="api.php" data-action="link_concern" data-id="<?= h($c['id']) ?>"><label class="form-label">Primary concern<select class="form-select" name="primaryConcernId" required><option value="">Choose the concern that represents the physical issue</option><?php foreach ($linkCandidates as $candidate): ?><option value="<?= h($candidate['id'] ?? '') ?>"><?= h(($candidate['id'] ?? '') . ' · ' . br_status_label($candidate['status'] ?? 'Submitted')) ?></option><?php endforeach ?></select></label><label class="form-label">Link note (optional)<textarea class="form-control" name="notes" maxlength="1000" rows="2" placeholder="Why these reports describe the same physical issue"></textarea></label><p class="form-text">The report and its reference number remain recorded. Work and public progress will follow the selected primary concern; a separate duplicate assignment will not be created.</p><button class="btn btn-light" type="submit">Link as same issue</button></form></details>
<?php endif ?>
<?php if (!$isLinkedConcern && in_array($c['status'], ['Under Review', 'Assigned', 'In Progress'], true) && $c['recommendation'] !== ''):
    $staff = array_filter(br_store()->workloads($actor['id']), fn($u) => $u['active']); $recommendedWorker = ConcernInsights::recommendPersonnel($staff,$c); ?>
<section class="action-panel"><h3>Assign / change personnel</h3><?php if ($recommendedWorker): ?><p class="priority-advice"><strong>Recommended personnel: <?= h($recommendedWorker['name']) ?></strong><br><?= (int)$recommendedWorker['active_work'] ?> active task(s) · <?= h($recommendedWorker['team']) ?><br><small>Relevant team first, then fewest active tasks. You can choose any active personnel below.</small></p><?php endif ?><form method="post" action="api.php" data-action="assign" data-id="<?= h($c['id']) ?>"><label class="form-label">Responsible personnel<select name="personnelId" class="form-select" required><option value="">Choose personnel</option><?php foreach ($staff as $u): ?><option value="<?= h($u['id']) ?>"<?= ($c['assignedUserId'] ?? '') === $u['id'] ? ' selected' : '' ?>><?= h($u['name'] . ' — ' . $u['team'] . ' · ' . $u['active_work'] . ' active · ' . ConcernInsights::workloadLabel((int)$u['active_work']) . (($recommendedWorker['id'] ?? '') === $u['id'] ? ' · Recommended' : '')) ?></option><?php endforeach ?></select></label><label class="form-label">Target completion (optional, Asia/Manila)<input type="datetime-local" class="form-control" name="dueAt" value="<?= !empty($c['dueAt']) ? h(date('Y-m-d\TH:i',(int)$c['dueAt'])) : '' ?>"></label><p class="form-text">The selected person receives an email and in-app notification. Reassignment removes the previous person's access and returns work to Assigned; earlier evidence stays in the timeline.</p><button class="btn btn-primary" type="submit">Save assignment</button></form></section>
<?php endif ?>
<?php if ($c['status'] === 'Resolved'): ?>
<section class="action-panel"><h3>Review completed work</h3><form method="post" action="api.php" data-action="verification" data-id="<?= h($c['id']) ?>"><label class="form-label">Review notes (required to reopen)<textarea class="form-control" id="feedback" name="feedback" maxlength="3000"></textarea></label><div class="d-flex gap-2 flex-wrap"><button class="btn btn-light" type="submit" value="reopen">Reopen Concern</button><button class="btn btn-primary" type="submit" value="verify">Close Concern</button></div></form></section>
<?php elseif (in_array($c['status'], ['Verified', 'Rejected', 'Referred to Another Office'], true)): ?>
<section class="action-panel"><h3>Reopen for assessment</h3><form method="post" action="api.php" data-action="reopen" data-id="<?= h($c['id']) ?>"><label class="form-label">Reason<textarea id="feedback" name="feedback" class="form-control" required maxlength="3000"></textarea></label><button type="submit" class="btn btn-light">Reopen Concern</button></form></section>
<?php elseif ($c['status'] === 'Returned for Information'): ?>
<section class="action-panel"><h3>Waiting for reporter information</h3><p>The request is available through the concern’s private tracking page. A response will be added to the timeline and return this concern to the assessment queue.</p></section>
<?php endif ?>
<details class="action-panel"><summary>Edit concern information / priority</summary><form class="mt-3" method="post" action="api.php" data-action="edit" data-id="<?= h($c['id']) ?>"><?php require __DIR__ . '/priority-recommendation.php'; ?>
<?php if (!empty($c['concernType'])) { br_concern_choices($c); br_location_fields($c['locationDetails']); } else { ?><label class="form-label">Category<select class="form-select" name="category" required><?php br_options(ComplaintWorkflow::CATEGORIES, $c['category']); ?></select></label><label class="form-label">Private location<input class="form-control" name="location" value="<?= h($c['location']) ?>" required maxlength="500"></label><?php } ?>
<label class="form-label">Priority<select class="form-select" name="priority" required><?php br_options(ComplaintWorkflow::PRIORITIES, $c['priority']); ?></select></label><label class="form-label">Additional details (optional)<textarea class="form-control" name="description" maxlength="4000"><?= h($c['description']) ?></textarea></label><label class="form-label">Official recommendation<textarea class="form-control" name="recommendation" maxlength="4000"><?= h($c['recommendation']) ?></textarea></label><button class="btn btn-primary" type="submit">Save concern information</button></form></details>
<?php endif ?>
<?php if ($currentBlock && $actor['role'] === 'official'): ?>
<section class="action-panel blocked-management"><h3>Manage blocked work</h3><div class="blocked-summary"><p><strong><?= h($currentBlock['reason'] ?? 'Blocked work') ?></strong></p><?php if (!empty($currentBlock['recommendedAction'])): ?><p>Recommended action: <?= h($currentBlock['recommendedAction']) ?></p><?php endif ?><?php if (!empty($currentBlock['expectedAt'])): ?><p>Expected availability: <?= h(br_date((string)$currentBlock['expectedAt'], true)) ?></p><?php endif ?></div><form method="post" action="api.php" data-action="manage_block" data-id="<?= h($c['id']) ?>"><label class="form-label">Official decision<select class="form-select" name="decision" required><option value="">Choose an action</option><option value="Approved">Approve requested action</option><option value="Declined">Decline requested action</option><option value="Instructions Updated">Send / update instructions</option><option value="Resume Work">Clear block and resume work</option></select></label><label class="form-label">Instructions / decision notes<textarea class="form-control" name="instructions" maxlength="3000" rows="3" required></textarea></label><label class="form-label">Updated target completion (optional, Asia/Manila)<input class="form-control" type="datetime-local" name="dueAt" value="<?= !empty($c['dueAt']) ? h(date('Y-m-d\TH:i', (int)$c['dueAt'])) : '' ?>"></label><button class="btn btn-primary" type="submit">Save blocked-work decision</button></form></section>
<?php endif ?>
<?php if (!$isLinkedConcern && in_array($c['status'], ['Assigned', 'In Progress'], true) && ($actor['role'] === 'official' || ComplaintWorkflow::canSee($c, $actor))): ?>
<?php if (!$currentBlock): ?>
<details class="action-panel"><summary>Mark work as blocked / delayed</summary><form class="mt-3" method="post" action="api.php" data-action="block" data-id="<?= h($c['id']) ?>"><label class="form-label">Block reason<select class="form-select" name="blockReason" required><option value="">Choose a reason</option><?php br_options(['Waiting for Materials', 'Requires Another Team', 'Weather Delay', 'Equipment Unavailable', 'Requires Official Approval', 'Other']); ?></select></label><label class="form-label">Notes (optional)<textarea class="form-control" name="blockNotes" maxlength="3000" rows="2"></textarea></label><label class="form-label">Recommended action<textarea class="form-control" name="recommendedAction" maxlength="2000" rows="2" required placeholder="What should happen before work can continue?"></textarea></label><label class="form-label">Expected availability (optional, Asia/Manila)<input class="form-control" type="datetime-local" name="expectedAt"></label><?php br_upload('block-photo', 'Supporting photo'); ?><p class="form-text">The reason, recommendations, expected date, and any supporting photo are recorded in the concern timeline. Officials will be notified.</p><button class="btn btn-light" type="submit">Mark as blocked</button></form></details>
<?php endif ?>
<?php foreach ($c['status'] === 'Assigned' ? ['start' => 'Start work'] : ['note' => 'Record progress', 'resolve' => 'Complete / resolve work'] as $action => $label): ?>
<?php $workStatuses = $action === 'resolve' ? ['Fully repaired'] : array_values(array_diff(ConcernCatalog::WORK_STATUSES, ['Materials required', 'Waiting for materials', 'Unable to complete', 'Requires another team'])); ?>
<section class="action-panel"><h3><?= h($label) ?></h3><?php if ($currentBlock): ?><p class="info-callout">This concern is currently marked blocked. Recording a new work update will indicate that work has resumed.</p><?php endif ?><form method="post" action="api.php" data-action="<?= $action ?>" data-id="<?= h($c['id']) ?>"><label class="form-label">Work status<select class="form-select" name="workStatus" required><?php br_options($workStatuses, $action === 'resolve' ? 'Fully repaired' : 'Arrived at location'); ?></select></label><fieldset class="mb-3"><legend class="form-label">Action taken (select at least one)</legend><div class="choice-grid"><?php foreach (ConcernCatalog::ACTIONS as $value): ?><label class="choice-card"><input class="form-check-input" type="checkbox" name="actions" value="<?= h($value) ?>"><span><?= h($value) ?></span></label><?php endforeach ?></div></fieldset><label class="form-label">Additional notes (optional; required for Other)<textarea class="form-control" name="notes" maxlength="4000" rows="2"></textarea></label><?php br_upload($action . '-photo', $action === 'resolve' ? 'Completion evidence' : 'Work evidence', true); ?><p class="form-text">Image evidence is required. The official reviews completed work before closing the concern.</p><button class="btn btn-primary" type="submit"><?= h($label) ?></button></form></section>
<?php endforeach; endif ?>
