<?php $role = $user['role'] ?? 'personnel'; $ownAccount = $user && $user['id'] === $actor['id']; ?>
<section class="panel form-page" id="account-form-panel">
  <form method="post" action="api.php" data-action="<?= $user ? 'update_user' : 'create_user' ?>"<?= $user ? ' data-id="' . h($user['id']) . '"' : '' ?>>
    <div class="new-form-body"><div class="row g-3">
      <?php if ($user): ?>
      <div class="col-12"><p class="info-callout mb-0"><?= h($user['email']) ?><br><?= $ownAccount ? 'You cannot deactivate or remove official access from your own account.' : 'Changes take effect on the account’s next request.' ?></p></div>
      <?php endif ?>
      <div class="col-sm-6"><label class="form-label" for="user-name">Full name</label><input class="form-control" id="user-name" name="name" required minlength="2" maxlength="100" autocomplete="off" value="<?= h($user['name'] ?? '') ?>"></div>
      <div class="col-sm-6"><label class="form-label" for="user-email">Email address</label><input class="form-control" id="user-email" name="email" type="email" required maxlength="254" autocomplete="off" value="<?= h($user['email'] ?? '') ?>"></div>
      <?php if (!$user): ?>
      <div class="col-12"><p class="info-callout mb-0">MaintainPro generates a temporary password. You will see it once after creating the account. The user must choose their own password at first sign-in.</p></div>
      <?php endif ?>
      <div class="col-sm-6"><label class="form-label" for="user-role">Account type</label><select class="form-select" id="user-role" name="role" required><?php foreach ($ownAccount ? ['official'] : ['resident', 'official', 'personnel'] as $option): ?><option value="<?= $option ?>"<?= $option === $role ? ' selected' : '' ?>><?= h(br_role($option)) ?></option><?php endforeach ?></select></div>
      <div class="col-sm-6" id="user-admin-wrap"<?= $role !== 'official' ? ' hidden' : '' ?>><label class="form-label" for="user-admin">System administration</label><select class="form-select" id="user-admin" name="isAdmin"<?= $ownAccount ? ' data-self="1" disabled' : '' ?>><option value="0"<?= empty($user['is_system_admin']) ? ' selected' : '' ?>>Standard official</option><option value="1"<?= !empty($user['is_system_admin']) ? ' selected' : '' ?>>System administrator</option></select><p class="form-text">Administrators can manage accounts, workspace settings, audit history, and backups.</p></div>
      <div class="col-sm-6" id="user-team-wrap"<?= $role !== 'personnel' ? ' hidden' : '' ?>><label class="form-label" for="user-team">Assigned team</label><select class="form-select" id="user-team" name="team"<?= $role === 'personnel' ? ' required' : '' ?>><?php br_options(ComplaintWorkflow::TEAMS, $user['team'] ?? '', 'Choose a team'); ?></select></div>
      <?php if ($user): ?><div class="col-sm-6"><label class="form-label" for="user-active">Account status</label><select class="form-select" id="user-active" name="active"><option value="1"<?= $user['active'] ? ' selected' : '' ?>>Active</option><?php if (!$ownAccount): ?><option value="0"<?= !$user['active'] ? ' selected' : '' ?>>Inactive</option><?php endif ?></select></div><?php endif ?>
      <?php if ($user && $user['role']==='personnel' && ($assignedWork['concerns'] || $assignedWork['actionPlans'])): ?>
      <div class="col-12"><div class="info-callout"><strong>Assigned work needs a new owner</strong><p class="mb-0">This person has <?= (int)$assignedWork['concerns'] ?> active concern(s) and <?= (int)$assignedWork['actionPlans'] ?> active action plan(s). If you deactivate this account, change its role, or move it to another team, choose another active personnel member. All active work will move together. Leave the account unchanged to cancel the move.</p></div></div>
      <div class="col-12"><label class="form-label" for="reassign-to">Reassign active work to</label><select class="form-select" id="reassign-to" name="reassignTo"><option value="">Choose a replacement when changing this account</option><?php foreach ($replacementWorkers as $worker): if (!$worker['active'] || $worker['id']===$user['id']) continue; ?><option value="<?= h($worker['id']) ?>"><?= h($worker['name'].' / '.$worker['team']) ?></option><?php endforeach ?></select><p class="form-text">Concern history and plan progress remain on the original records.</p></div>
      <?php endif ?>
      <div class="col-12"><label class="form-label" for="administrator-password">Your current password</label><input class="form-control" id="administrator-password" name="current_password" type="password" autocomplete="current-password" required maxlength="72"><p class="form-text">Confirm your administrator password before creating an account or changing another account's access.</p></div>
    </div></div>
    <div class="form-footer"><small><?= $user ? 'Existing concern records are retained.' : 'Each account keeps its own role and reporting allowance.' ?></small><button class="btn btn-primary" type="submit"><?= $user ? 'Save account settings' : 'Create account' ?></button></div>
  </form>
</section>
