<?php
declare(strict_types=1);
require __DIR__ . '/includes/public-layout.php';
br_public_header('Report and track barangay concerns'); ?>
<section class="public-hero"><div><span class="eyebrow">MAINTAINPRO</span><h1>Report and Track Barangay Concerns</h1><p>Report community maintenance concerns and track their progress in one place.</p><div class="d-flex flex-wrap gap-3"><a class="btn btn-primary btn-lg" href="report-concern.php">Report a Concern</a><a class="btn btn-light btn-lg" href="track.php">Track a Concern</a><a class="btn btn-light btn-lg" href="login.php">Sign In</a></div><p class="form-text mt-3">Guests can report without an account. Exact locations and evidence remain private.</p></div><div class="hero-emblem" aria-hidden="true"><?= br_icon('building') ?><span>Report.<br>Respond.<br>Resolve.</span></div></section>
<section class="landing-categories" aria-labelledby="category-heading"><div class="section-heading"><h2 id="category-heading" class="section-title">What do you want to report?</h2><p>Choose a category to start with it already selected.</p></div><div class="category-card-grid"><?php foreach (array_keys(ConcernCatalog::TYPES) as $category): ?><a class="category-card" href="<?= h(br_url('report-concern.php',['category'=>$category])) ?>"><?= br_icon(match($category){'Roads and Infrastructure'=>'tool','Drainage/Flooding','Water'=>'inbox','Waste Management','Sanitation'=>'refresh','Street Lighting'=>'flag','Public Facilities'=>'building','Safety'=>'shield','Environmental Concern'=>'book',default=>'clipboard'}) ?><span><?= h($category) ?></span><small><?= count(ConcernCatalog::TYPES[$category]) ?> concern types</small></a><?php endforeach ?></div></section>
<section class="row g-4 public-steps" aria-label="How reporting works"><?php foreach (['1. Report' => 'Choose the concern, give its location, and add a photo when available.', '2. Barangay response' => 'An official reviews the concern and assigns personnel to act.', '3. Track the result' => 'Use your private reference and tracking code to follow updates through closure.'] as $title => $copy): ?><div class="col-md-4"><article class="panel h-100 p-4"><h2 class="section-title"><?= h($title) ?></h2><p class="mb-0 text-muted"><?= h($copy) ?></p></article></div><?php endforeach ?></section>
<p class="info-callout mt-4">For immediate danger, contact local emergency services directly. MaintainPro reports are reviewed by barangay staff.</p>
<?php br_public_footer(); ?>
