<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/store.php';
require __DIR__ . '/support/database.php';
$test = new TestDatabase(); $checks = 0;
function check(bool $ok, string $label): void { global $checks; if (!$ok) throw new RuntimeException('FAIL: ' . $label); $checks++; }
function denied(callable $call, string $label): void { try { $call(); } catch (DomainException $e) { check(true, $label); return; } throw new RuntimeException('FAIL: expected denial: ' . $label); }
try {
    $store = new ComplaintStore($test->connect());
    check($store->needsSetup(), 'empty setup');
    $admin = $store->setup(['name' => 'Test Official', 'email' => 'official@example.test', 'password' => 'Official-password-42']);
    denied(fn() => $store->setup([]), 'setup once');
    denied(fn() => $store->register([]), 'resident registration retired');
    denied(fn() => $store->createUser($admin['id'], ['role' => 'resident']), 'no new resident accounts');
    foreach (['bad', 'x@', ''] as $email) denied(fn() => $store->createUser($admin['id'], ['name' => 'Bad Staff', 'role' => 'personnel', 'team' => 'Maintenance crew', 'email' => $email]), 'invalid staff email');
    $staff = $store->createUser($admin['id'], ['name' => 'Test Staff', 'email' => 'staff@example.test', 'role' => 'personnel', 'team' => 'Maintenance crew']);
    check($staff['must_change_password'] && strlen($staff['temporary_password']) >= 20, 'random temporary credential');
    denied(fn() => $store->createUser($staff['id'], []), 'personnel cannot manage accounts');
    denied(fn() => $store->changeTemporaryPassword($staff['id'], ['current_password' => 'wrong']), 'onboarding current password');
    $active = $store->changeTemporaryPassword($staff['id'], ['current_password' => $staff['temporary_password'], 'password' => 'Staff-password-42', 'confirm_password' => 'Staff-password-42']);
    check(!$active['must_change_password'], 'onboarding done');
    check($store->login('STAFF@example.test', 'Staff-password-42', 'test')['id'] === $staff['id'], 'staff normalized login');
    denied(fn() => $store->login('staff@example.test', $staff['temporary_password'], 'test'), 'old temporary password invalid');
    denied(fn() => $store->updateUser($admin['id'], $staff['id'], ['role' => 'personnel', 'team' => 'Maintenance crew', 'active' => '1', 'email' => 'invalid']), 'edit email validates');
    denied(fn() => $store->updateUser($admin['id'], $admin['id'], ['role' => 'official', 'active' => '0']), 'own deactivation blocked');
    $store->updateUser($admin['id'], $staff['id'], ['role' => 'personnel', 'team' => 'Maintenance crew', 'active' => '1', 'name' => 'Renamed Staff', 'email' => 'updated@example.test']);
    check($store->user($staff['id'])['email'] === 'updated@example.test', 'staff identity editable');
    $report = ['category' => 'Street Lighting', 'concernType' => 'Light not working', 'keyPoints' => ['Completely dark', 'Near pedestrian crossing'], 'purok' => 'Private Purok', 'street' => 'Private Street', 'exactArea' => 'Private gate'];
    $receipt = $store->submitGuest($report, 'guest-1'); $id = $receipt['reference'];
    $c = $store->state()['cases'][0];
    check($c['title'] === 'Light not working Concern' && $c['residentId'] === null, 'guest stored without account');
    check(!str_contains(json_encode($store->state()), $receipt['trackingCode']), 'tracking secret not in staff state');
    $tracked = $store->track($id, $receipt['trackingCode'], 'track1');
    check(!str_contains(json_encode($tracked), 'Private') && !isset($tracked['timeline']), 'tracking safe allowlist');
    denied(fn() => $store->track($id, str_repeat('0', 48), 'track1'), 'wrong code denied');
    $other = $store->submitGuest($report, 'guest-2');
    denied(fn() => $store->track($other['reference'], $receipt['trackingCode'], 'track1'), 'code bound to reference');
    $store->mutate($admin['id'], 'assess', $id, ['priority' => 'High', 'recommendation' => 'Private instruction'], 1);
    denied(fn() => $store->mutate($admin['id'], 'assess', $id, ['priority' => 'Low', 'recommendation' => 'Stale'], 1), 'stale version blocked');
    denied(fn() => $store->mutate($admin['id'], 'assign', $id, ['personnelId' => $admin['id'], '_assignee' => $staff], 2), 'forged internal assignee blocked');
    $store->mutate($admin['id'], 'assign', $id, ['personnelId' => $staff['id']], 2);
    check(count(ComplaintWorkflow::visible($store->state(), $active)) === 1, 'personnel sees assigned case only');
    $edit = array_replace($report, ['priority' => 'Urgent', 'description' => '', 'recommendation' => 'Updated official plan', 'exactArea' => 'Updated private gate']);
    $store->mutate($admin['id'], 'edit', $id, $edit, 3);
    $edited = array_values(array_filter($store->state()['cases'], fn($c) => $c['id'] === $id))[0];
    check($edited['priority'] === 'Urgent' && $edited['locationDetails']['exactArea'] === 'Updated private gate' && $edited['assignedUserId'] === $staff['id'], 'official edits priority/location while preserving assignment');
    check(end($edited['timeline'])['changes']['before']['priority'] === 'High', 'edit audit preserves original information');
    denied(fn() => $store->mutate($staff['id'], 'edit', $id, $edit, 4), 'personnel cannot edit official information');
    $rules = $report + ['action1' => 'Inspect fixture safely.', 'action2' => 'Check supply using qualified personnel.', 'action3' => 'Schedule suitable repair.'];
    denied(fn() => $store->saveRule($staff['id'], $rules), 'staff cannot edit public rules');
    $store->saveRule($admin['id'], $rules);
    check($store->suggestions($report)[0] === 'Inspect fixture safely.', 'curated library used');
    $store->saveRule($admin['id'], $rules, true);
    check($store->suggestions($report)[0] !== 'Inspect fixture safely.', 'built-in defaults restored');
    for ($i = 0; $i < 5; $i++) $store->publicLimit('report', 'limited-client');
    denied(fn() => $store->submitGuest($report, 'limited-client'), 'report throttle');
    denied(fn() => $store->submitGuest($report + ['website' => 'spam'], 'honeypot'), 'honeypot');
    for ($i = 0; $i < 5; $i++) denied(fn() => $store->login('updated@example.test', 'wrong', 'login-limit'), 'wrong login');
    denied(fn() => $store->login('updated@example.test', 'Staff-password-42', 'login-limit'), 'login throttle');
    $store->updateUser($admin['id'], $staff['id'], ['role' => 'personnel', 'team' => 'Maintenance crew', 'active' => '0']);
    check($store->actor($staff['id']) === null, 'deactivated actor denied');
    denied(fn() => $store->mutate($staff['id'], 'start', $id, [], 3), 'deactivated writes denied');
    denied(fn() => $store->mutate($admin['id'], 'assign', $id, ['personnelId' => $staff['id']], 4), 'cannot assign inactive personnel');
    $reopened = new ComplaintStore($test->connect());
    check(count($reopened->state()['cases']) === 2, 'database persistence');
    DatabaseMaintenance::initialize($test->connect());
    check(count($reopened->state()['cases']) === 2, 'migration repeat preserves records');
    echo "PASS: $checks store, account, tracking, rule and abuse checks.\n";
} finally { $test->drop(); }
