<?php
declare(strict_types=1);
date_default_timezone_set('Asia/Manila');
require dirname(__DIR__).'/includes/store.php';
require __DIR__.'/support/database.php';
$test=new TestDatabase(); $checks=0; $archive=null;
function upgradeCheck(bool $ok,string $label): void { global $checks; if(!$ok) throw new RuntimeException('FAIL: '.$label); $checks++; }
function upgradeDenied(callable $call,string $label): void { try { $call(); } catch(DomainException) { upgradeCheck(true,$label); return; } throw new RuntimeException('FAIL: expected denial: '.$label); }
try {
    $migrationText="-- Example\nSELECT 1;\n";
    upgradeCheck(DatabaseMaintenance::migrationChecksumMatches(str_replace("\n","\r\n",$migrationText),hash('sha256',$migrationText)),'LF migration survives CRLF checkout');
    upgradeCheck(DatabaseMaintenance::migrationChecksumMatches($migrationText,hash('sha256',str_replace("\n","\r\n",$migrationText))),'CRLF historical checksum survives LF checkout');
    upgradeCheck(!DatabaseMaintenance::migrationChecksumMatches(str_replace('1','2',$migrationText),hash('sha256',$migrationText)),'migration checksum still rejects SQL edits');
    $store=new ComplaintStore($test->connect()); $db=new MaintainProDatabase($test->connect()); $fixtures=new DatabaseTestFixtures($test->connect());
    $password='Upgrade-password-42';
    $official=$store->setup(['name'=>'Upgrade Official','email'=>'official@example.test','password'=>$password]);
    $resident=$store->register(['name'=>'Private Reporter','email'=>'resident@example.test','password'=>$password]);
    $other=$store->register(['name'=>'Other Reporter','email'=>'other@example.test','password'=>$password]);
    $staff=$store->createUser($official['id'],['name'=>'Upgrade Staff','email'=>'staff@example.test','role'=>'personnel','team'=>'Maintenance crew']);
    $staff=activateInvitedUser($store,$staff,$password);
    $report=['category'=>'Street Lighting','concernType'=>'Exposed wiring','keyPoints'=>['Sparks visible'],'purok'=>'Original name','street'=>'Mabini St.','exactArea'=>'PRIVATE GATE'];
    $png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=';
    $store->createLocation($official['id'],['name'=>'Purok One']);
    $location=$store->locations()[0]; $report['locationId']=(string)$location['id'];
    $id=$store->submitAccount($resident['id'],$report+['photo'=>$png]);
    $find=fn(string $reference)=>$store->concernForActor($official['id'],$reference);
    $change=function(array $actor,string $ref,string $action,array $data=[]) use($store,$find) { $store->mutate($actor['id'],$action,$ref,$data,$find($ref)['version']); return $find($ref); };
    $original=$find($id);
    DatabaseMaintenance::initialize($test->connect());
    $fixtures->repeatUpgradeMigration();
    upgradeCheck($find($id)===$original,'repeated migration preserves concern');
    $keys=$fixtures->upgradeConstraints();
    foreach(['complaints:resident_id','concern_tracking:complaint_id','notifications:user_id','notifications:related_concern_id','password_resets:user_id','concern_feedback:complaint_id','weekly_action_plans:assigned_user_id'] as $expected) {
        upgradeCheck(in_array($expected,array_map(fn($r)=>$r['TABLE_NAME'].':'.$r['COLUMN_NAME'],$keys),true),'foreign key '.$expected);
    }
    try { $fixtures->invalidPayload($id); throw new RuntimeException('Invalid JSON accepted'); } catch(PDOException) { upgradeCheck(true,'database rejects invalid concern JSON'); }
    try { $fixtures->orphanNotification(); throw new RuntimeException('Orphan accepted'); } catch(PDOException) { upgradeCheck(true,'database rejects orphan notification'); }
    $receipt=$store->submitGuest(array_replace($report,['street'=>'mabini street']),'guest-match'); $duplicate=$receipt['reference'];
    $store->updateLocation($official['id'],(int)$location['id'],['name'=>'Renamed Purok','sortOrder'=>0]);
    $third=$store->submitGuest(array_replace($report,['street'=>'  MABINI  ST  ']),'guest-third')['reference'];
    upgradeCheck(count($store->relatedConcerns($official['id'],$id))===3,'recurrence normalizes abbreviations and survives Purok rename');
    upgradeCheck(count($store->possibleDuplicates($official['id'],$id))===2,'automatic duplicate suggestions');
    upgradeCheck($find($duplicate)['status']==='Submitted','suggestion never changes status');
    upgradeDenied(fn()=>$store->possibleDuplicates($staff['id'],$id),'duplicate suggestions official only');
    upgradeDenied(fn()=>$store->dismissDuplicate($resident['id'],$id,['candidateId'=>$duplicate]),'reporter cannot dismiss duplicate');
    $store->dismissDuplicate($official['id'],$id,['candidateId'=>$duplicate]);
    upgradeCheck(!in_array($duplicate,array_column($store->possibleDuplicates($official['id'],$id),'id'),true),'dismissal hides pair');
    upgradeCheck(!in_array($id,array_column($store->possibleDuplicates($official['id'],$duplicate),'id'),true),'dismissal symmetric');
    upgradeDenied(fn()=>$store->dismissDuplicate($official['id'],$id,['candidateId'=>'missing']),'forged candidate rejected');
    $change($official,$third,'link_concern',['primaryConcernId'=>$id]);
    upgradeCheck($find($third)['status']==='Linked to Primary','existing manual linking still works');
    $inbox=$store->notifications($resident['id']);
    upgradeCheck(count($inbox['items'])===1 && str_contains($inbox['items'][0]['target_url'],$id),'reporter receipt notification and own detail link');
    upgradeCheck(!str_contains(json_encode($inbox),'PRIVATE GATE'),'notification excludes private location');
    $raw=array_values(array_filter($store->state()['cases'],fn($c)=>$c['id']===$id))[0];
    (new ConcernNotifications($db))->changed($raw,null,'submit');
    upgradeCheck(count($store->notifications($resident['id'])['items'])===1,'notification event replay deduplicated');
    $change($official,$id,'request_information',['notes'=>'Please clarify the pole.']);
    upgradeCheck($store->concernForActor($resident['id'],$id)['reporterChannel']==='account','account request response channel');
    $change($resident,$id,'information',['description'=>'Second pole.']);
    $dates=ConcernInsights::recommendedDates();
    upgradeCheck(strtotime($dates['Urgent'])<strtotime($dates['High']) && strtotime($dates['High'])<strtotime($dates['Medium']) && strtotime($dates['Medium'])<strtotime($dates['Low']),'central priority SLA order');
    upgradeDenied(fn()=>$change($official,$id,'assess',['priority'=>'Urgent','recommendation'=>'Inspect','dueAt'=>'2026-02-31T12:00']),'invalid SLA date');
    $change($official,$id,'assess',['priority'=>'Urgent','recommendation'=>'Inspect safely','dueAt'=>$dates['Urgent']]);
    upgradeCheck($find($id)['dueAt']===strtotime($dates['Urgent']),'official accepts SLA without automatic resolution');
    $change($official,$id,'assign',['team'=>'Maintenance crew','dueAt'=>$dates['High']]);
    $store->mutate($staff['id'],'accept_work',$id,[],null);
    $work=['photo'=>$png,'workStatus'=>'Inspection completed','actions'=>['Inspection']];
    $change($staff,$id,'start',$work);
    upgradeDenied(fn()=>$store->submitFeedback($resident['id'],$id,['rating'=>'5']),'feedback unavailable before resolution');
    $change($staff,$id,'resolve',array_replace($work,['workStatus'=>'Fully repaired','actions'=>['Repair']]));
    $change($official,$id,'verify');
    upgradeDenied(fn()=>$store->submitFeedback($other['id'],$id,['rating'=>'5']),'other reporter cannot rate');
    upgradeDenied(fn()=>$store->submitFeedback($staff['id'],$id,['rating'=>'5']),'worker cannot rate');
    upgradeDenied(fn()=>$store->submitFeedback($resident['id'],$id,['rating'=>'6']),'rating upper bound');
    upgradeCheck($store->concernFeedback($resident['id'],$id)['canSubmit'],'original reporter can rate completed concern');
    $store->submitFeedback($resident['id'],$id,['rating'=>'4','comment'=>'<script>private feedback</script>']);
    upgradeDenied(fn()=>$store->submitFeedback($resident['id'],$id,['rating'=>'2']),'feedback replay denied');
    upgradeCheck($store->concernFeedback($staff['id'],$id)['feedback']===null,'feedback private from assigned personnel');
    upgradeCheck((int)$store->feedbackAnalytics($official['id'])['summary']['responses']===1,'feedback analytics count');
    upgradeCheck((float)$store->feedbackAnalytics($official['id'])['summary']['average']===4.0,'feedback analytics average');
    upgradeDenied(fn()=>$store->feedbackAnalytics($resident['id']),'feedback analytics official only');
    $own=$store->submitAccount($staff['id'],$report);
    $change($official,$own,'assess',['priority'=>'High','recommendation'=>'Inspect']);
    $change($official,$own,'assign',['team'=>'Maintenance crew']);
    $store->mutate($staff['id'],'accept_work',$own,[],null);
    $change($staff,$own,'start',$work); $change($staff,$own,'resolve',array_replace($work,['workStatus'=>'Fully repaired']));
    upgradeDenied(fn()=>$store->submitFeedback($staff['id'],$own,['rating'=>'5']),'personnel reporter cannot rate own work');
    $rules=$store->officialRules($official['id'],'Street Lighting','Exposed wiring','Sparks visible');
    upgradeCheck(count($rules)===3,'official library seeded separately');
    $guidance=$store->suggestions($report);
    $ruleData=['category'=>'Street Lighting','concernType'=>'Exposed wiring','keypoint'=>'Sparks visible','revision'=>ComplaintStore::ruleRevision($rules),
        'action1'=>'New first staff action','action2'=>'New second staff action','action3'=>'Inactive staff action','active1'=>'1','active2'=>'1'];
    upgradeDenied(fn()=>$store->saveOfficialRules($staff['id'],$ruleData),'personnel cannot edit official library');
    $store->saveOfficialRules($official['id'],$ruleData);
    upgradeDenied(fn()=>$store->saveOfficialRules($official['id'],$ruleData),'stale official library edit rejected');
    upgradeCheck($store->suggestions($report)===$guidance,'resident guidance unaffected');
    $weekly=$store->weeklyConcerns($official['id']);
    upgradeCheck($weekly['groups'][0]['actions']===['New first staff action','New second staff action'],'weekly actions use active database rules in order');
    $rules=$store->officialRules($official['id'],'Street Lighting','Exposed wiring','Sparks visible');
    $planData=['ruleId'=>(string)$rules[0]['id'],'ruleVersion'=>(string)$rules[0]['version'],'title'=>'Make wiring safe','notes'=>'Coordinate visit','team'=>'Maintenance crew','personnelId'=>$staff['id'],'targetDate'=>date('Y-m-d',time()+86400),'requestKey'=>str_repeat('c',64)];
    upgradeDenied(fn()=>$store->saveActionPlan($staff['id'],0,$planData),'personnel cannot create plan');
    upgradeDenied(fn()=>$store->saveActionPlan($official['id'],0,array_replace($planData,['team'=>'Sanitation team'])),'plan assignee team validated');
    upgradeDenied(fn()=>$store->saveActionPlan($official['id'],0,array_replace($planData,['ruleId'=>$rules[2]['id']])),'inactive solution rejected');
    $planId=$store->saveActionPlan($official['id'],0,$planData);
    upgradeDenied(fn()=>$store->saveActionPlan($official['id'],0,array_replace($planData,['ruleVersion'=>'1','requestKey'=>str_repeat('d',64)])),'changed selected solution rejected');
    upgradeCheck($store->saveActionPlan($official['id'],0,$planData)===$planId && $store->actionPlans($official['id'])['total']===1,'replayed create yields one action plan');
    $plan=$store->actionPlan($official['id'],$planId);
    upgradeCheck($plan['selected_solution']==='New first staff action' && $plan['status']==='Planned','plan snapshot and initial status');
    $planData+=['status'=>'Ongoing','version'=>'1'];
    $store->saveActionPlan($official['id'],$planId,$planData);
    upgradeDenied(fn()=>$store->saveActionPlan($official['id'],$planId,$planData),'stale plan edit denied');
    $planData['version']='2'; $planData['status']='Completed';
    upgradeDenied(fn()=>$store->saveActionPlan($official['id'],$planId,$planData),'completion outcome required');
    $planData['outcome']='Isolated fault and repaired wiring.'; $store->saveActionPlan($official['id'],$planId,$planData);
    upgradeCheck($store->actionPlan($official['id'],$planId)['completed_at']!==null && $store->actionPlans($official['id'],'Completed')['total']===1,'completed plan retained in history');
    $ruleData['revision']=ComplaintStore::ruleRevision($rules); $ruleData['action1']='Changed later'; $store->saveOfficialRules($official['id'],$ruleData);
    upgradeCheck($store->actionPlan($official['id'],$planId)['selected_solution']==='New first staff action','plan retains selected solution history after library edit');
    for($i=0;$i<24;$i++) $store->submitGuest(array_replace($report,['street'=>'Other road '.$i]),'paging-'.$i);
    $page1=$store->pagedConcerns($official['id'],['category'=>'Street Lighting'],1,10);
    $page2=$store->pagedConcerns($official['id'],['category'=>'Street Lighting'],2,10);
    upgradeCheck($page1['total']===28 && count($page1['items'])===10 && count($page2['items'])===10,'SQL total and bounded page sizes');
    upgradeCheck(!array_intersect(array_column($page1['items'],'id'),array_column($page2['items'],'id')),'SQL pages do not overlap');
    upgradeCheck($store->pagedConcerns($official['id'],[],999,10)['page']===3,'out of range page clamped');
    upgradeCheck($store->pagedConcerns($official['id'],['personnel'=>$staff['id'],'status'=>'Verified','priority'=>'Urgent','team'=>'Maintenance crew'])['total']===1,'combined personnel team priority status filters');
    upgradeCheck($store->pagedConcerns($resident['id'],[])['total']===1,'resident paging scope');
    upgradeCheck($store->pagedConcerns($resident['id'],['search'=>"' OR 1=1 --"])['total']===0,'prepared search handles injection text');
    upgradeCheck($store->concernForActor($other['id'],$id)===null,'single concern authorization');
    $public=json_encode($store->publicStatistics());
    foreach(['PRIVATE GATE','Mabini','Private Reporter','private feedback','example.test',$id] as $secret) upgradeCheck(!str_contains($public,$secret),'public aggregation excludes '.$secret);
    upgradeDenied(fn()=>$store->generateFullBackup($staff['id']),'full backup official only');
    $archive=$store->generateFullBackup($official['id']); $zip=new PharData($archive['path']);
    upgradeCheck(isset($zip['database.sql']) && isset($zip['RESTORE.txt']),'ZIP contains database and restore instructions');
    $sql=$zip['database.sql']->getContent();
    upgradeCheck(!str_contains($sql,$db->passwordHash($official['id'])) && str_contains($sql,'!reset-required'),'full backup excludes password hashes');
    $evidence=$store->evidenceRecord($official['id'],$find($id)['initialEvidenceId']);
    upgradeCheck(isset($zip[$evidence['file_path']]),'ZIP contains evidence');
    foreach(new RecursiveIteratorIterator($zip) as $entry) upgradeCheck(!preg_match('~(?:\.env|mail\.local|session|\.tmp|\.php)$~',$entry->getFilename()),'ZIP allowlist entry');
    $restoreName='maintainpro_test_'.bin2hex(random_bytes(8)); DatabaseMaintenance::create($restoreName);
    try {
        $restore=$test->connect(); $restore=br_database($restoreName); (new DatabaseTestFixtures($restore))->restoreBackup($sql);
        DatabaseMaintenance::initialize($restore); $restored=new ComplaintStore($restore);
        upgradeCheck(count($restored->state()['cases'])===28 && $restored->actionPlans($official['id'])['total']===1,'ZIP SQL restores concerns and plans');
        upgradeCheck($restored->track($duplicate,$receipt['trackingCode'],'restore')['reference']===$duplicate,'guest tracking survives restore');
        upgradeDenied(fn()=>$restored->login($official['email'],$password,'restore'),'old password invalid after credential-free restore');
    } finally { DatabaseMaintenance::dropTestDatabase($restoreName); }
    unset($zip); unlink($archive['path']); $archive=null;
    upgradeCheck($store->auditLogs($official['id'],['action'=>'full_backup_created'])['total']===1,'full backup audit');
    upgradeCheck($store->auditLogs($official['id'],['action'=>'resolution_feedback_submitted'])['total']===1,'feedback audit');
    $legacyId=bin2hex(random_bytes(16)); $fixtures->legacyEvidence($id,$legacyId,$png);
    upgradeCheck($store->legacyEvidence($resident['id'],$legacyId)===$png,'legacy image loads through single concern lookup');
    upgradeCheck($store->legacyEvidence($other['id'],$legacyId)===null,'legacy image lookup preserves authorization');
    $fixtures->removeOfficialRole(); upgradeCheck(!$store->needsSetup(),'setup latch prevents reactivation after all officials removed');
    upgradeDenied(fn()=>$store->setup(['name'=>'Second Official','email'=>'second@example.test','password'=>$password]),'setup never reopened');
    echo "PASS: $checks system upgrade, privacy, migration, pagination, planning, feedback and ZIP restoration checks.\n";
} finally { if($archive && is_file($archive['path'])) unlink($archive['path']); $test->drop(); }
