<?php
declare(strict_types=1);
if (!isset($testDatabase,$isolatedStore)) throw new RuntimeException('Run through tests/http.php.');
foreach(['official-solutions.php','action-plans.php'] as $path) {
    pageDocument($adminJar,$path);
    pageDocument($reporterJar,$path,403);
    pageDocument($reportStaffJar,$path,403);
    httpCheck(str_contains(req($guestJar,$path)['body'],'data-action="login"'),'guest blocked from '.$path);
}
$rules=$isolatedStore->officialRules($officialId,'Waste Management','Uncollected garbage','Bad odor');
$ruleData=['category'=>'Waste Management','concernType'=>'Uncollected garbage','keypoint'=>'Bad odor',
    'revision'=>ComplaintStore::ruleRevision($rules),'action1'=>'Arrange collection and inspect the source.','action2'=>'Clean the public area.','action3'=>'Monitor collection frequency.','active1'=>'1','active2'=>'1','active3'=>'1'];
httpCheck(post($adminJar,'save_official_rules',$ruleData,'')['status']===403,'official library CSRF');
httpCheck(post($reportStaffJar,'save_official_rules',$ruleData,$reportStaffCsrf)['status']===422,'official library API guard');
httpCheck(post($adminJar,'save_official_rules',$ruleData,$adminCsrf)['status']===200,'official library update API');
httpCheck(post($adminJar,'save_official_rules',$ruleData,$adminCsrf)['status']===409,'official library stale-edit response');
$planData=['ruleId'=>(string)$rules[0]['id'],'ruleVersion'=>(string)((int)$rules[0]['version']+1),'title'=>'Weekly collection','notes'=>'Inspect public site.','team'=>'Maintenance crew','personnelId'=>$reportStaff['id'],'targetDate'=>date('Y-m-d',time()+86400),'requestKey'=>bin2hex(random_bytes(32))];
pageHas(pageDocument($adminJar,'action-plans.php?rule='.$rules[0]['id']),'//form[@data-action="create_action_plan"]','selected action plan form');
httpCheck(post($reporterJar,'create_action_plan',$planData,$reporterCsrf)['status']===422,'resident cannot create action plan');
httpCheck(post($adminJar,'create_action_plan',$planData,'')['status']===403,'action plan CSRF');
$create=post($adminJar,'create_action_plan',$planData,$adminCsrf);
httpCheck($create['status']===200,'action plan creation endpoint'); $planId=$create['json']['id'];
httpCheck(post($adminJar,'create_action_plan',$planData,$adminCsrf)['json']['id']===$planId,'action-plan create replay');
pageHas(pageDocument($adminJar,'action-plans.php?id='.$planId),'//form[@data-action="update_action_plan"]','plan edit form');
pageDocument($adminJar,'action-plans.php?week='.ConcernInsights::week()['date']);
$planData+=['status'=>'Completed','outcome'=>'Area cleaned.','version'=>'1'];
httpCheck(post($adminJar,'update_action_plan',$planData,$adminCsrf,$planId)['status']===200,'plan completion API');
httpCheck(post($adminJar,'update_action_plan',$planData,$adminCsrf,$planId)['status']===409,'plan stale edit API');
httpCheck(str_contains(req($adminJar,'action-plans.php?status=Completed')['body'],'Weekly collection'),'completed plan retained');
$reportId=$reportedIds[0];
pageHas(pageDocument($adminJar,'concern.php?id='.$reportId),'//button[@data-accept-sla]','SLA recommendation UI');
httpCheck(str_contains(req($adminJar,'concern.php?id='.$reportId)['body'],'MaintainPro account/dashboard'),'information request account instructions');
httpCheck(str_contains(req($adminJar,'concern.php?id='.$reportId)['body'],'Possible Existing Concern'),'possible duplicate UI');
httpCheck(post($reportStaffJar,'dismiss_duplicate',['candidateId'=>$reportedIds[1]],$reportStaffCsrf,$reportId)['status']===422,'personnel cannot dismiss suggestion');
httpCheck(post($adminJar,'dismiss_duplicate',['candidateId'=>$reportedIds[1]],$adminCsrf,$reportId)['status']===200,'keep separate API');
httpCheck($save($adminJar,$adminCsrf,'request_information',$reportId,['notes'=>'Please clarify the collection point.'])['status']===200,'account information request');
pageHas(pageDocument($reporterJar,'concern.php?id='.$reportId),'//form[@data-action="information"]','reporter can respond from details');
httpCheck($save($reporterJar,$reporterCsrf,'information',$reportId,['description'=>'Public collection point.'])['status']===200,'account response endpoint');
$save($adminJar,$adminCsrf,'assess',$reportId,['priority'=>'Medium','recommendation'=>'Inspect and clean.','dueAt'=>date('Y-m-d\TH:i',time()+86400)]);
$save($adminJar,$adminCsrf,'assign',$reportId,['personnelId'=>$reportStaff['id']]);
$work=['photo'=>$png,'workStatus'=>'Inspection completed','actions'=>['Inspection']];
httpCheck($save($reportStaffJar,$reportStaffCsrf,'start',$reportId,$work)['status']===200,'new reporter workflow starts');
httpCheck($save($reportStaffJar,$reportStaffCsrf,'resolve',$reportId,array_replace($work,['workStatus'=>'Fully repaired']))['status']===200,'new reporter workflow resolves');
httpCheck($save($adminJar,$adminCsrf,'verify',$reportId)['status']===200,'new reporter workflow closes');
pageHas(pageDocument($reporterJar,'concern.php?id='.$reportId),'//form[@data-action="submit_feedback"]','reporter feedback form');
httpCheck(post($reporterJar,'submit_feedback',['rating'=>'5'],'',$reportId)['status']===403,'feedback CSRF');
httpCheck(post($reportStaffJar,'submit_feedback',['rating'=>'5'],$reportStaffCsrf,$reportId)['status']===422,'worker feedback denied');
httpCheck(post($reporterJar,'submit_feedback',['rating'=>'5','comment'=>'<script>feedback private</script>'],$reporterCsrf,$reportId)['status']===200,'feedback endpoint');
httpCheck(post($reporterJar,'submit_feedback',['rating'=>'5'],$reporterCsrf,$reportId)['status']===422,'feedback endpoint replay denied');
$feedbackPage=req($adminJar,'reports.php');
httpCheck($feedbackPage['status']===200,'feedback report renders');
httpCheck(str_contains($feedbackPage['body'],'&lt;script&gt;feedback private&lt;/script&gt;'),'feedback comments escaped');
$publicStats=pageDocument($guestJar,'transparency.php')->evaluate('string(//main)');
foreach(['PRIVATE','feedback private','Reporting Resident HTTP','Reporting Personnel HTTP','@example.test'] as $secret) httpCheck(!str_contains($publicStats,$secret),'public dashboard excludes '.$secret);
httpCheck(req($reporterJar,'api.php?view=notifications')['json']['unread']>=6,'reporter receives lifecycle notifications');
$full=backupRequest($adminJar,$adminCsrf,'full');
httpCheck($full['status']===200 && str_starts_with($full['body'],'PK'),'full backup ZIP download');
httpCheck(backupRequest($reportStaffJar,$reportStaffCsrf,'full')['status']===403,'full backup staff blocked');
httpCheck(backupRequest($adminJar,'','full')['status']===403,'full backup CSRF');
for($i=0;$i<25;$i++) $isolatedStore->submitGuest(array_replace($accountReport,['street'=>'Pagination street '.$i]),'upgrade-http-'.$i);
$list=pageDocument($adminJar,'complaints.php?category=Waste%20Management');
httpCheck($list->query('//table[contains(@class,"complaint-table")]/tbody/tr')->length===20,'concern page SQL page size');
pageHas($list,'//nav[@aria-label="Result pages"]//a[contains(.,"Next")]','pagination next link');
$next=pageDocument($adminJar,'complaints.php?category=Waste%20Management&p=2');
httpCheck($next->query('//table[contains(@class,"complaint-table")]/tbody/tr')->length>0,'second page records');
pageHas($next,'//nav[@aria-label="Result pages"]//a[contains(.,"Previous")]','pagination previous link');
