<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/domain.php';
$checks = 0;
function check(bool $ok, string $label): void { global $checks; if (!$ok) throw new RuntimeException('FAIL: ' . $label); $checks++; }
function denied(callable $call, string $label): void { try { $call(); } catch (DomainException $e) { check(true, $label); return; } throw new RuntimeException('FAIL: expected denial: ' . $label); }
$guest = ['id' => null, 'name' => 'Anonymous resident', 'role' => 'guest'];
$official = ['id' => 'official', 'name' => 'Official', 'role' => 'official', 'team' => ''];
$staff = ['id' => 'staff', 'name' => 'Personnel', 'role' => 'personnel', 'team' => 'Maintenance crew', 'active' => true];
$other = array_replace($staff, ['id' => 'other']);
$report = ['category' => 'Roads and Infrastructure', 'concernType' => 'Pothole', 'keyPoints' => ['Deep', 'Near intersection'], 'purok' => 'Purok 2', 'street' => 'Test Street', 'exactArea' => 'Near test court'];
$photo = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=';
$state = ['nextId' => 1, 'cases' => []];
$report['_suggestions'] = ConcernCatalog::suggestions($report['category'], $report['concernType'], $report['keyPoints']);
$id = ComplaintWorkflow::submit($state, $guest, $report);
check(str_starts_with($id, 'CON-' . date('Y') . '-000001'), 'reference format');
$c = $state['cases'][0];
check($c['title'] === 'Pothole Concern' && $c['description'] === '' && $c['residentId'] === null, 'anonymous generated title and optional details');
check($c['keyPoints'] === $report['keyPoints'] && count($c['suggestions']) === 3, 'structured selections and exactly three suggestions');
foreach (['purok', 'street', 'exactArea', 'category', 'concernType'] as $field) denied(function () use (&$state, $guest, $report, $field) { ComplaintWorkflow::submit($state, $guest, array_replace($report, [$field => ''])); }, 'required ' . $field);
denied(function () use (&$state, $guest, $report) { ComplaintWorkflow::submit($state, $guest, array_replace($report, ['keyPoints' => ['Forged']])); }, 'unknown points');
denied(function () use (&$state, $official, $report) { ComplaintWorkflow::submit($state, $official, $report); }, 'staff cannot impersonate guest action');
check(!ComplaintWorkflow::canSee($c, $staff), 'unassigned location inaccessible');
ComplaintWorkflow::apply($state, $official, $id, 'assess', ['priority' => 'High', 'recommendation' => 'Inspect and repair.']);
ComplaintWorkflow::apply($state, $official, $id, 'assign', ['_assignee' => $staff]);
check(ComplaintWorkflow::canSee($state['cases'][0], $staff) && !ComplaintWorkflow::canSee($state['cases'][0], $other), 'specific personnel only even on same team');
$work = ['workStatus' => 'Inspection completed', 'actions' => ['Inspection'], 'photo' => $photo];
foreach (['', 'data:image/png;base64,' . base64_encode('<?php echo 1; ?>'), 'data:image/svg+xml;base64,' . base64_encode('<svg/>')] as $bad) denied(function () use (&$state, $staff, $id, $work, $bad) { ComplaintWorkflow::apply($state, $staff, $id, 'start', array_replace($work, ['photo' => $bad])); }, 'required real image');
check($state['cases'][0]['status'] === 'Assigned', 'failed update atomic');
ComplaintWorkflow::apply($state, $staff, $id, 'start', $work);
denied(function () use (&$state, $other, $id, $work) { ComplaintWorkflow::apply($state, $other, $id, 'note', $work); }, 'same team cannot act');
denied(function () use (&$state, $staff, $id, $work) { ComplaintWorkflow::apply($state, $staff, $id, 'note', array_replace($work, ['actions' => []])); }, 'structured action required');
ComplaintWorkflow::apply($state, $staff, $id, 'note', $work);
denied(function () use (&$state, $staff, $id, $work) { ComplaintWorkflow::apply($state, $staff, $id, 'resolve', $work); }, 'cannot resolve inspection alone');
ComplaintWorkflow::apply($state, $staff, $id, 'resolve', array_replace($work, ['workStatus' => 'Fully repaired', 'actions' => ['Repair']]));
$event = end($state['cases'][0]['timeline']);
check($event['actorId'] === 'staff' && strlen($event['evidenceId']) === 32 && $event['photo'] === $photo && $event['actions'] === ['Repair'], 'evidence bound to actor and structured event');
denied(function () use (&$state, $staff, $id) { ComplaintWorkflow::apply($state, $staff, $id, 'verify', []); }, 'personnel cannot close own outcome');
ComplaintWorkflow::apply($state, $official, $id, 'verify', []);
check($state['cases'][0]['status'] === 'Verified', 'official closes');
ComplaintWorkflow::apply($state, $official, $id, 'reopen', ['feedback' => 'Issue returned']);
check($state['cases'][0]['reopenCount'] === 1 && !ComplaintWorkflow::canSee($state['cases'][0], $staff), 'reopen needs fresh assessment and assignment');
ComplaintWorkflow::apply($state, $official, $id, 'exception', ['status' => 'Returned for Information', 'notes' => 'Inspect exact area']);
ComplaintWorkflow::apply($state, $official, $id, 'information', ['notes' => 'Area checked']);
check($state['cases'][0]['status'] === 'Submitted', 'staff follow-up preserved');
foreach (ConcernCatalog::TYPES as $category => $types) foreach ($types as $type) check(count(ConcernCatalog::suggestions($category, $type, [])) === 3, 'rules for ' . $type);
echo "PASS: $checks workflow, structured validation, evidence and authorization checks.\n";
